version: '3.7'

services:
  app:
    build:
      context: .
    command: php -S 0.0.0.0:8000 -t /var/www/app/public
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"

  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'default'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'